@extends('layouts.admin')
@section('title', $isEditing ? 'Editar publicación' : 'Nueva publicación')
@section('content')
<div class="mx-auto max-w-5xl space-y-6"><div><x-breadcrumb :items="[['label' => 'Publicaciones', 'url' => route('admin.posts.index')], ['label' => $isEditing ? 'Editar' : 'Nueva']]"/><h1 class="mt-3 font-display text-headline-xl-mobile font-bold text-slate-900 sm:text-headline-xl">{{ $isEditing ? 'Editar publicación' : 'Nueva publicación' }}</h1></div>
@if($errors->any())<x-alert variant="danger"><ul class="list-inside list-disc">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></x-alert>@endif
<x-card><form action="{{ $isEditing ? route('admin.posts.update', $post) : route('admin.posts.store') }}" method="POST" enctype="multipart/form-data" class="space-y-5">@csrf @if($isEditing)@method('PUT')@endif
<div class="grid gap-5 md:grid-cols-2"><div class="md:col-span-2"><x-input name="title" label="Título" maxlength="180" required :value="old('title', $post->title)"/></div><div class="md:col-span-2"><x-textarea name="excerpt" label="Resumen" maxlength="320" rows="2" required>{{ old('excerpt', $post->excerpt) }}</x-textarea></div><div class="md:col-span-2"><x-textarea name="body" label="Contenido" maxlength="50000" rows="12" required hint="Se presenta como texto; HTML y scripts se escapan.">{{ old('body', $post->body) }}</x-textarea></div>
<x-select name="category_id" label="Categoría" required><option value="">Selecciona una categoría</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected((string) old('category_id', $post->category_id)===(string) $category->id)>{{ $category->name }}{{ !$category->active ? ' (inactiva)' : '' }}</option>@endforeach</x-select>
<x-select name="status" label="Estado editorial" required>@foreach(['draft'=>'Borrador','review'=>'En revisión','published'=>'Publicada','archived'=>'Archivada'] as $status=>$label)<option value="{{ $status }}" @selected(old('status', $post->status ?: 'draft')===$status)>{{ $label }}</option>@endforeach</x-select>
<x-input name="published_at" label="Publicar en (opcional)" type="datetime-local" :value="old('published_at', $post->published_at?->format('Y-m-d\TH:i'))" hint="Si se deja vacío al publicar, se usa la hora actual."/>
<div><label for="cover" class="mb-1.5 block text-sm font-medium text-slate-700">Imagen de portada (opcional)</label><input id="cover" name="cover" type="file" accept="image/jpeg,image/png,image/webp" class="block w-full rounded-md border border-slate-300 bg-white px-3 py-2 text-sm">@error('cover')<p class="text-xs text-rose-700">{{ $message }}</p>@enderror</div><x-input name="cover_alt" label="Texto alternativo" maxlength="180" :value="old('cover_alt', $post->cover_alt)"/></div>
@if($isEditing && $post->cover_path)<img src="{{ Storage::disk('public')->url($post->cover_path) }}" alt="{{ $post->cover_alt }}" class="max-h-56 rounded-lg object-cover">@endif
<div class="flex justify-end gap-3 border-t border-slate-200 pt-5"><a href="{{ route('admin.posts.index') }}"><x-button variant="secondary">Cancelar</x-button></a><x-button type="submit">Guardar publicación</x-button></div></form></x-card></div>
@endsection
