@extends('layouts.admin')
@section('title', 'Categorías')
@section('content')
<div class="mx-auto max-w-7xl space-y-6">
    <header class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><x-breadcrumb :items="[['label' => 'Contenido'], ['label' => 'Categorías']]"/><h1 class="mt-3 font-display text-headline-xl-mobile font-bold text-slate-900 sm:text-headline-xl">Categorías</h1><p class="mt-2 text-sm text-slate-600">Organiza las publicaciones por tema.</p></div><a href="{{ route('admin.categories.create') }}"><x-button>＋ Nueva categoría</x-button></a></header>
    @if(session('success'))<x-alert variant="success">{{ session('success') }}</x-alert>@endif
    <x-card><form method="GET" class="grid gap-3 sm:grid-cols-[1fr_12rem_auto]"><x-input name="search" label="Nombre" :value="$filters['search'] ?? ''"/><x-select name="status" label="Estado"><option value="">Todos</option><option value="active" @selected(($filters['status'] ?? '')==='active')>Activas</option><option value="inactive" @selected(($filters['status'] ?? '')==='inactive')>Inactivas</option></x-select><x-button type="submit" variant="secondary">Filtrar</x-button></form></x-card>
    <x-card padding="none">@if($categories->isEmpty())<div class="p-8"><x-empty-state title="No hay categorías" description="Crea una categoría para clasificar noticias."><a href="{{ route('admin.categories.create') }}"><x-button size="sm">Crear categoría</x-button></a></x-empty-state></div>@else<x-table><thead><tr><th class="px-5 py-3 text-left">Categoría</th><th class="px-5 py-3 text-left">Slug</th><th class="px-5 py-3 text-left">Publicaciones</th><th class="px-5 py-3 text-left">Estado</th><th class="px-5 py-3 text-right">Acciones</th></tr></thead><tbody>@foreach($categories as $category)<tr><td class="px-5 py-4"><span class="font-medium text-slate-900">{{ $category->name }}</span>@if($category->description)<span class="mt-1 block text-xs text-slate-500">{{ $category->description }}</span>@endif</td><td class="px-5 py-4 font-mono text-xs">{{ $category->slug }}</td><td class="px-5 py-4">{{ $category->posts_count }}</td><td class="px-5 py-4"><x-badge :variant="$category->active ? 'success' : 'neutral'">{{ $category->active ? 'Activa' : 'Inactiva' }}</x-badge></td><td class="px-5 py-4"><div class="flex justify-end gap-2"><a href="{{ route('admin.categories.edit', $category) }}"><x-button size="sm" variant="secondary">Editar</x-button></a><form action="{{ route('admin.categories.destroy', $category) }}" method="POST" onsubmit="return confirm('¿Eliminar esta categoría? Las publicaciones quedarán sin categoría.')">@csrf @method('DELETE')<x-button type="submit" size="sm" variant="danger">Eliminar</x-button></form></div></td></tr>@endforeach</tbody></x-table><div class="px-5 py-4">{{ $categories->links() }}</div>@endif</x-card>
</div>
@endsection
